services:
  - type: web
    name: vaani
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/service_account.json
    secretFiles:
      - path: /etc/secrets/service_account.json
        envVar: GOOGLE_APPLICATION_CREDENTIALS
